config:
  protocol: tree
  log_dir: ./logs
  log_level:
    websocket_server: info
    alice: info
    charlie: info
ports:
  - name: alice
    ip: 127.0.0.1
    port: 55550
    type: client
  - name: charlie
    ip: 127.0.0.1
    port: 55550
    type: server