config:
  protocol: tree
  web_socket_port: 6364
  log_dir: /opt/hermes/logs
  log_level:
    websocket_server: info
    alice: info
    charlie: info
  node_id: sumanth
ports:
  - name: en1
    interface: "127.0.0.1:8001:8002"
  - name: en2
    interface: "127.0.0.1:8003:8004"