config:
  protocol: tree
  log_dir: /opt/hermes/logs
  log_level:
    websocket_server: info
    alice: info
    charlie: info
  node_id: sahas
ports:
  - name: en2
    interface: en2
  - name: en3
    interface: en3
  - name: en4
    interface: en4